# alpine - is linux distributive about 5mb
image: node:10-alpine


variables:
  USER: fenricage

# guarantee consistent execution instead of parallel
stages:
  - test
  - package

test:
  stage: test
  script: echo 'TEEEEST'
