# alpine - is linux distributive about 5mb
image: node:10-alpine


variables:
  USER: fenricage

# guarantee consistent execution instead of parallel
stages:
  - test
  - package

echo_test:
  stage: test
  script: echo 'TEEEEST'

echo_test2:
  stage: test
  script: echo 'TEEEEST 222222222222222'
